module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5871',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5871/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5871/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5871/events',
    html_url: 'https://github.com/iptv-org/database/issues/5871',
    id: 1929261634,
    node_id: 'I_kwDOG1Kwp85y_jJC',
    number: 5871,
    title: 'Remove: 002 Radio TV',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      },
      {
        id: 6049155772,
        node_id: 'LA_kwDOG1Kwp88AAAABaI7KvA',
        url: 'https://api.github.com/repos/iptv-org/database/labels/blocklist:add',
        name: 'channels:remove',
        color: 'e99695',
        default: false,
        description: 'Request to remove a channel'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T00:35:32Z',
    updated_at: '2023-10-06T00:35:32Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel ID\n\n002RadioTV.do\n\n### Reason\n\nOther\n\n### Notes (optional)\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5871/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5871/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
