module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5900',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5900/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5900/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5900/events',
    html_url: 'https://github.com/iptv-org/database/issues/5900',
    id: 1929321995,
    node_id: 'I_kwDOG1Kwp85y_x4L',
    number: 5900,
    title: 'Add: Yiwu News Integrated Channel',
    user: {
      login: 'AntiPontifex',
      id: 81566772,
      node_id: 'MDQ6VXNlcjgxNTY2Nzcy',
      avatar_url: 'https://avatars.githubusercontent.com/u/81566772?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/AntiPontifex',
      html_url: 'https://github.com/AntiPontifex',
      followers_url: 'https://api.github.com/users/AntiPontifex/followers',
      following_url: 'https://api.github.com/users/AntiPontifex/following{/other_user}',
      gists_url: 'https://api.github.com/users/AntiPontifex/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/AntiPontifex/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/AntiPontifex/subscriptions',
      organizations_url: 'https://api.github.com/users/AntiPontifex/orgs',
      repos_url: 'https://api.github.com/users/AntiPontifex/repos',
      events_url: 'https://api.github.com/users/AntiPontifex/events{/privacy}',
      received_events_url: 'https://api.github.com/users/AntiPontifex/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5303575699,
        node_id: 'LA_kwDOG1Kwp88AAAABPB4kkw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/channels:add',
        name: 'channels:add',
        color: '017ff8',
        default: false,
        description: 'Request to add a channel into the database'
      },
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T02:10:41Z',
    updated_at: '2023-10-06T02:52:02Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel Name\n\nYiwu News Integrated Channel\n\n### Alternative Names (optional)\n\n_No response_\n\n### Network (optional)\n\n_No response_\n\n### Owners (optional)\n\n_No response_\n\n### Country\n\nCN\n\n### Subdivision (optional)\n\n_No response_\n\n### City (optional)\n\n_No response_\n\n### Broadcast Area\n\nc/CN\n\n### Languages\n\nzho\n\n### Categories (optional)\n\nnews\n\n### NSFW\n\nFALSE\n\n### Launched (optional)\n\n_No response_\n\n### Closed (optional)\n\n_No response_\n\n### Replaced By (optional)\n\n_No response_\n\n### Website (optional)\n\n_No response_\n\n### Logo\n\nhttps://www.tvchinese.net/uploads/tv/yiwutv.jpg\n\n### Notes\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5900/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5900/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5899',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5899/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5899/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5899/events',
    html_url: 'https://github.com/iptv-org/database/issues/5899',
    id: 1929318573,
    node_id: 'I_kwDOG1Kwp85y_xCt',
    number: 5899,
    title: 'Add: Yiwu Business Channel',
    user: {
      login: 'AntiPontifex',
      id: 81566772,
      node_id: 'MDQ6VXNlcjgxNTY2Nzcy',
      avatar_url: 'https://avatars.githubusercontent.com/u/81566772?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/AntiPontifex',
      html_url: 'https://github.com/AntiPontifex',
      followers_url: 'https://api.github.com/users/AntiPontifex/followers',
      following_url: 'https://api.github.com/users/AntiPontifex/following{/other_user}',
      gists_url: 'https://api.github.com/users/AntiPontifex/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/AntiPontifex/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/AntiPontifex/subscriptions',
      organizations_url: 'https://api.github.com/users/AntiPontifex/orgs',
      repos_url: 'https://api.github.com/users/AntiPontifex/repos',
      events_url: 'https://api.github.com/users/AntiPontifex/events{/privacy}',
      received_events_url: 'https://api.github.com/users/AntiPontifex/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5303575699,
        node_id: 'LA_kwDOG1Kwp88AAAABPB4kkw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/channels:add',
        name: 'channels:add',
        color: '017ff8',
        default: false,
        description: 'Request to add a channel into the database'
      },
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T02:05:11Z',
    updated_at: '2023-10-06T02:51:46Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel Name\n\nYiwu Business Channel\n\n### Alternative Names (optional)\n\n_No response_\n\n### Network (optional)\n\n_No response_\n\n### Owners (optional)\n\n_No response_\n\n### Country\n\nCN\n\n### Subdivision (optional)\n\n_No response_\n\n### City (optional)\n\n_No response_\n\n### Broadcast Area\n\nc/CN\n\n### Languages\n\nzho\n\n### Categories (optional)\n\nbusiness\n\n### NSFW\n\nFALSE\n\n### Launched (optional)\n\n_No response_\n\n### Closed (optional)\n\n_No response_\n\n### Replaced By (optional)\n\n_No response_\n\n### Website (optional)\n\n_No response_\n\n### Logo\n\nhttps://www.tvchinese.net/uploads/tv/yiwutv.jpg\n\n### Notes\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5899/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5899/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5898',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5898/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5898/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5898/events',
    html_url: 'https://github.com/iptv-org/database/issues/5898',
    id: 1929313117,
    node_id: 'I_kwDOG1Kwp85y_vtd',
    number: 5898,
    title: 'Add: Wenzhou Economic and Education',
    user: {
      login: 'AntiPontifex',
      id: 81566772,
      node_id: 'MDQ6VXNlcjgxNTY2Nzcy',
      avatar_url: 'https://avatars.githubusercontent.com/u/81566772?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/AntiPontifex',
      html_url: 'https://github.com/AntiPontifex',
      followers_url: 'https://api.github.com/users/AntiPontifex/followers',
      following_url: 'https://api.github.com/users/AntiPontifex/following{/other_user}',
      gists_url: 'https://api.github.com/users/AntiPontifex/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/AntiPontifex/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/AntiPontifex/subscriptions',
      organizations_url: 'https://api.github.com/users/AntiPontifex/orgs',
      repos_url: 'https://api.github.com/users/AntiPontifex/repos',
      events_url: 'https://api.github.com/users/AntiPontifex/events{/privacy}',
      received_events_url: 'https://api.github.com/users/AntiPontifex/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5303575699,
        node_id: 'LA_kwDOG1Kwp88AAAABPB4kkw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/channels:add',
        name: 'channels:add',
        color: '017ff8',
        default: false,
        description: 'Request to add a channel into the database'
      },
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T01:56:32Z',
    updated_at: '2023-10-06T02:51:22Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel Name\n\nWenzhou Economic and Education\n\n### Alternative Names (optional)\n\n_No response_\n\n### Network (optional)\n\n_No response_\n\n### Owners (optional)\n\n_No response_\n\n### Country\n\nCN\n\n### Subdivision (optional)\n\n_No response_\n\n### City (optional)\n\nWenzhou\n\n### Broadcast Area\n\nc/CN\n\n### Languages\n\nzho\n\n### Categories (optional)\n\nscience\n\n### NSFW\n\nFALSE\n\n### Launched (optional)\n\n_No response_\n\n### Closed (optional)\n\n_No response_\n\n### Replaced By (optional)\n\n_No response_\n\n### Website (optional)\n\n_No response_\n\n### Logo\n\nhttps://www.tvchinese.net/uploads/tv/wzjjkj.jpg\n\n### Notes\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5898/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5898/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
