module.exports = [
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5901',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5901/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5901/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5901/events',
    html_url: 'https://github.com/iptv-org/database/issues/5901',
    id: 1929459171,
    node_id: 'I_kwDOG1Kwp85zATXj',
    number: 5901,
    title: 'Edit: M5',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5303574335,
        node_id: 'LA_kwDOG1Kwp88AAAABPB4fPw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/channels:edit',
        name: 'channels:edit',
        color: 'E12977',
        default: false,
        description: 'Request to edit channel description'
      },
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T05:25:44Z',
    updated_at: '2023-10-06T05:25:44Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel ID (required)\n\nM5.hu\n\n### Channel Name\n\n_No response_\n\n### Alternative Names\n\n_No response_\n\n### Network\n\n_No response_\n\n### Owners\n\nDuna Médiaszolgáltató Nonprofit Zrt.\n\n### Country\n\n_No response_\n\n### Subdivision\n\n_No response_\n\n### City\n\n_No response_\n\n### Broadcast Area\n\n_No response_\n\n### Languages\n\n_No response_\n\n### Categories\n\n~\n\n### NSFW\n\nNone\n\n### Launched\n\n_No response_\n\n### Closed\n\n~\n\n### Replaced By\n\n_No response_\n\n### Website\n\n_No response_\n\n### Logo\n\n_No response_\n\n### Notes\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5901/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5901/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/database/issues/5701',
    repository_url: 'https://api.github.com/repos/iptv-org/database',
    labels_url: 'https://api.github.com/repos/iptv-org/database/issues/5701/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/database/issues/5701/comments',
    events_url: 'https://api.github.com/repos/iptv-org/database/issues/5701/events',
    html_url: 'https://github.com/iptv-org/database/issues/5701',
    id: 1929459171,
    node_id: 'I_kwDOG1Kwp85zATXj',
    number: 5701,
    title: 'Edit: M5',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      site_admin: false
    },
    labels: [
      {
        id: 5303574335,
        node_id: 'LA_kwDOG1Kwp88AAAABPB4fPw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/channels:edit',
        name: 'channels:edit',
        color: 'E12977',
        default: false,
        description: 'Request to edit channel description'
      },
      {
        id: 5366738347,
        node_id: 'LA_kwDOG1Kwp88AAAABP-Htqw',
        url: 'https://api.github.com/repos/iptv-org/database/labels/approved',
        name: 'approved',
        color: '85DDDE',
        default: false,
        description: ''
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-10-06T05:25:44Z',
    updated_at: '2023-10-06T05:25:44Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Channel ID (required)\n\nBeijingSatelliteTV.cn\n\n### Channel Name\n\nbeIN Movies Turk\n\n### Alternative Names\n\nbeIN Movies Türk\n\n### Network\n\nBBC\n\n### Owners\n\nGazprom Media\n\n### Country\n\nTR\n\n### Subdivision\n\nUS-CA\n\n### City\n\nLondon\n\n### Broadcast Area\n\nc/TR\n\n### Languages\n\ntur\n\n### Categories\n\nmovies\n\n### NSFW\nTRUE\n\n### Launched\n\n1979-05-16\n\n### Closed\n\n1980-05-16\n\n### Replaced By\n\nM5.hu\n\n### Website\n\nhttp://www.digiturk.com.tr/\n\n### Logo\n\nhttps://i.imgur.com/nw8Sa2z.png\n\n### Notes\n\n_No response_',
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/database/issues/5701/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/database/issues/5701/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
