name: '➕ blocklist/add'
description: Request to add a channel to the blocklist
title: 'Block: '
labels: ['blocklist:add']

body:
  - type: input
    id: channel
    attributes:
      label: Channel ID
      description: The ID of the channel that should be blocked
      placeholder: 'AnhuiTV.cn'
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Reason
      description: Reason for blocking the channel
      options:
        - 'DMCA'
        - 'NSFW'
    validations:
      required: true

  - type: input
    id: ref
    attributes:
      label: Reference
      description: Link to DMCA notice or approved channel removal request
      placeholder: 'https://github.com/iptv-org/iptv/issues/1831'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes (optional)
      description: 'Anything else we should know?'
