name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: export data to ./api
        run: npm run db:export
      - uses: JamesIves/github-pages-deploy-action@164583b9e44b4fc5910e78feb607ea7c98d3c7b9 # 4.1.1
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' }}
        with:
          repository-name: paulysid/api
          branch: gh-pages
          folder: .api
          token: ${{ secrets.API_REPO_TOKEN }}
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to paulysid/api'
          clean: false